const binding = require('../binding')

module.exports = {
  signals: {
    SIGHUP: binding.SIGHUP,
    SIGINT: binding.SIGINT,
    SIGQUIT: binding.SIGQUIT,
    SIGILL: binding.SIGILL,
    SIGTRAP: binding.SIGTRAP,
    SIGABRT: binding.SIGABRT,
    SIGIOT: binding.SIGIOT,
    SIGBUS: binding.SIGBUS,
    SIGFPE: binding.SIGFPE,
    SIGKILL: binding.SIGKILL,
    SIGUSR1: binding.SIGUSR1,
    SIGSEGV: binding.SIGSEGV,
    SIGUSR2: binding.SIGUSR2,
    SIGPIPE: binding.SIGPIPE,
    SIGALRM: binding.SIGALRM,
    SIGTERM: binding.SIGTERM,
    SIGCHLD: binding.SIGCHLD,
    SIGSTKFLT: binding.SIGSTKFLT,
    SIGCONT: binding.SIGCONT,
    SIGSTOP: binding.SIGSTOP,
    SIGTSTP: binding.SIGTSTP,
    SIGBREAK: binding.SIGBREAK,
    SIGTTIN: binding.SIGTTIN,
    SIGTTOU: binding.SIGTTOU,
    SIGURG: binding.SIGURG,
    SIGXCPU: binding.SIGXCPU,
    SIGXFSZ: binding.SIGXFSZ,
    SIGVTALRM: binding.SIGVTALRM,
    SIGPROF: binding.SIGPROF,
    SIGWINCH: binding.SIGWINCH,
    SIGIO: binding.SIGIO,
    SIGPOLL: binding.SIGPOLL,
    SIGLOST: binding.SIGLOST,
    SIGPWR: binding.SIGPWR,
    SIGINFO: binding.SIGINFO,
    SIGSYS: binding.SIGSYS,
    SIGUNUSED: binding.SIGUNUSED
  }
}
